version: '2'
services:
  db2:
    image: redis
     links:
      - 'db'
      - 'db:some-weird-host'
      - 'web:three-changing-the-weird-host'
    ports:
      - "6379:6379"
  db:
    image: mongo
    ports:
      - "27017:27017"
  web:
    build: .
    ports:
      - "3000:3000"
    links:
      - "db"
    environment:
      - MONGODB_HOST=db
